# Generated by Django 5.2.8 on 2025-11-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateField(verbose_name='Data da Movimentação'),
        ),
    ]
